title: La Danza de las Fieras
baseurl: "/"
description: >
  Seis historias. Seis directores. La Danza de las Fieras es una
  película que aborda diferentes caras de la trata de personas.
url: "http://ladanzadelasfieras.com/" # the base hostname & protocol for your site, e.g. http://example.com
facebook: https://www.facebook.com/ladanzadelasfieras/
imdb: http://www.imdb.com/title/tt7072396/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  cortometrajes:
    output: false
  noticias:
    output: true
    permalink: /noticias/:path/

google_analytics: "UA-58263416-1"
sass:
  style: compressed
